# Dependencies
version:     3.1
markdown:    redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments

# Permalinks
permalink:   /blog/:title

# Setup
title:       WP_UnitTestCase Documentation (Unofficial)
description: 'Unofficial Documentation'
url:         'http://miya.io'
